
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Stack;
import javax.swing.table.DefaultTableModel;


public class Interfaz_Principal extends javax.swing.JFrame {
    private File f;
    private FileReader entrada;
    private BufferedReader br;
    private DefaultTableModel mTabla;
    private lexico lex;
    private Sintactico sintactico;
    ArrayList <String []> filas;
    /** Creates new form Interfaz_Principal */
    public Interfaz_Principal() {
        mTabla=new DefaultTableModel (new Object [] {"TOKEN","LEXEMA"},0);
        lex= new lexico();

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        path = new javax.swing.JFileChooser();
        lbTitulo = new javax.swing.JLabel();
        lbNomArchivo = new javax.swing.JLabel();
        pnlOpciones = new javax.swing.JPanel();
        btAbrir = new javax.swing.JButton();
        btALexico = new javax.swing.JButton();
        btASintactico = new javax.swing.JButton();
        txtArchivo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbALexico = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaArchivoFuente = new javax.swing.JTextArea();
        lbArchivoFuente = new javax.swing.JLabel();
        lbConsola = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaConsolaErrores = new javax.swing.JTextArea();

        path.setCurrentDirectory(null);
        path.setAutoscrolls(true);
        path.getAccessibleContext().setAccessibleDescription("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador Sintáctico 2012 FCC BUAP");

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 24));
        lbTitulo.setForeground(new java.awt.Color(0, 51, 102));
        lbTitulo.setText("Analizador Sintáctico");

        lbNomArchivo.setText("Nombre del Archivo: ");

        pnlOpciones.setBackground(new java.awt.Color(204, 204, 204));

        btAbrir.setFont(new java.awt.Font("Tahoma", 0, 14));
        btAbrir.setForeground(new java.awt.Color(0, 51, 102));
        btAbrir.setText("Abrir");
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });

        btALexico.setFont(new java.awt.Font("Tahoma", 0, 14));
        btALexico.setForeground(new java.awt.Color(0, 51, 102));
        btALexico.setText("Analizador Léxico");
        btALexico.setEnabled(false);
        btALexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btALexicoActionPerformed(evt);
            }
        });

        btASintactico.setFont(new java.awt.Font("Tahoma", 0, 14));
        btASintactico.setForeground(new java.awt.Color(0, 51, 102));
        btASintactico.setText("Analizador Sintáctico");
        btASintactico.setEnabled(false);
        btASintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btASintacticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpcionesLayout = new javax.swing.GroupLayout(pnlOpciones);
        pnlOpciones.setLayout(pnlOpcionesLayout);
        pnlOpcionesLayout.setHorizontalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btALexico, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(btAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(btASintactico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlOpcionesLayout.setVerticalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btALexico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btASintactico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
        );

        txtArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArchivoActionPerformed(evt);
            }
        });

        tbALexico.setModel(mTabla);
        jScrollPane1.setViewportView(tbALexico);

        txaArchivoFuente.setColumns(20);
        txaArchivoFuente.setRows(5);
        jScrollPane2.setViewportView(txaArchivoFuente);

        lbArchivoFuente.setText("Fuente: ");

        lbConsola.setText("Consola: ");

        txaConsolaErrores.setColumns(20);
        txaConsolaErrores.setRows(5);
        jScrollPane3.setViewportView(txaConsolaErrores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbConsola)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                                    .addComponent(lbArchivoFuente)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(lbNomArchivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(512, 512, 512)
                        .addComponent(lbTitulo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbArchivoFuente)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbConsola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(pnlOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArchivoActionPerformed

    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed
        // TODO add your handling code here:
        try{
            path.showOpenDialog(path);
            this.txtArchivo.setText(path.getSelectedFile().getAbsolutePath());
            this.agregar();
        }catch (NullPointerException as){
            this.txtArchivo.setText("");
            this.btALexico.setEnabled (false);
            JOptionPane.showMessageDialog(null, "No seleccionó ningún archivo", "Mensaje", JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null,"No selecciono Archivo","Mensaje",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btAbrirActionPerformed

    private void btALexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btALexicoActionPerformed
        // TODO add your handling code here:
        filas=lex.analizar(this.txtArchivo.getText());
        for (int i=0;i<filas.size();i++){
            Object [] obj= new Object []{filas.get(i)[0],filas.get(i)[1]};
            mTabla.addRow(obj);
        }
        if (lex.isCorrecto())
            this.btASintactico.setEnabled(true);


    }//GEN-LAST:event_btALexicoActionPerformed

    private void btASintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btASintacticoActionPerformed
        // TODO add your handling code here:
        //sintactico=new Sintactico(filas);
        String []aux={"$","$"};//Se añade el final de la cadena para que pueda ser analaizado por el analizador sintactico
        filas.add(aux);
        ArrayList <String []> filas2=new ArrayList();
        for (int i=0;i<filas.size();i++){
            if (!filas.get(i)[0].equals("COMENTARIO"))
                filas2.add(filas.get(i));
        }
        SintacticoTabla sintactico2=new SintacticoTabla(filas2);

        String resultado=sintactico2.AnalizadorSintactico();
        this.txaConsolaErrores.setText(resultado);

        //sintactico.S();
    }//GEN-LAST:event_btASintacticoActionPerformed

    //Funcion para agregar el contenido del archivo en el Area de texto
    private void agregar(){
        boolean flag=true;
        try{
          f=new File(this.txtArchivo.getText());
          entrada=new FileReader(f);
          br = new BufferedReader(entrada);

          this.txaArchivoFuente.setText("");
          String linea="";
          while ((linea = br.readLine()) != null)
          this.txaArchivoFuente.append(linea+"\n");

        }
            catch(IOException ass){
                JOptionPane.showMessageDialog(null,ass.toString(),"Mensaje",JOptionPane.ERROR_MESSAGE);
                this.txtArchivo.setText("");
                //analizar.setEnabled(false);
                btALexico.setEnabled(false);
                flag=false;
            }
            finally {

            try {
                if (null != entrada) {entrada.close();}
                if(flag){
                    //analizar.setEnabled(true);
                    btALexico.setEnabled(true);
                }
            } catch (Exception aaa) {JOptionPane.showMessageDialog(null,aaa.toString(),"Mensaje",JOptionPane.ERROR_MESSAGE);
                this.txtArchivo.setText("");
                //analizar.setEnabled(false);
                btALexico.setEnabled(false);
            }
            }///finally


    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btALexico;
    private javax.swing.JButton btASintactico;
    private javax.swing.JButton btAbrir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbArchivoFuente;
    private javax.swing.JLabel lbConsola;
    private javax.swing.JLabel lbNomArchivo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JFileChooser path;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JTable tbALexico;
    private javax.swing.JTextArea txaArchivoFuente;
    private javax.swing.JTextArea txaConsolaErrores;
    private javax.swing.JTextField txtArchivo;
    // End of variables declaration//GEN-END:variables

}
